version: '3'
services:
  todo-api:
  #  image: gudditi/todo-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "80:3000"
    environment:
      MONGO_URI: "mongodb+srv://test:test@mongo.0yvjyh0.mongodb.net/?retryWrites=true&w=majority"
      PORT: "3000"